/**
 * Learn & Go - Базовая грамматика (Глаголы движения без префиксов)
 * Файл: data_verbs.js
 */

const upr = [
    // УРОК 1 (Индекс 0): ИДТИ • ЕХАТЬ (30 вопросов)
    [
        { exver: "Урок 1: ИДТИ • ЕХАТЬ (пешком или транспорт)" },
        { id: "v1_1", ex: "Я сейчас ________ в магазин пешком.", ans: ["иду", "еду"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city", "mark_now"] },
        { id: "v1_2", ex: "Моя подруга ________ в парк пешком.", ans: ["идёт", "едет"], tags: ["mode_foot", "dir_uni", "time_present", "dom_nature"] },
        { id: "v1_3", ex: "Маленькая девочка ________ в школу пешком.", ans: ["идёт", "едет"], tags: ["mode_foot", "dir_uni", "time_present", "dom_social"] },
        { id: "v1_4", ex: "Я ________ на почту, она рядом с домом.", ans: ["иду", "еду"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city", "logic_near"] },
        { id: "v1_5", ex: "Мы ________ в музей пешком.", ans: ["идём", "едем"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_6", ex: "Эти люди ________ на стадион пешком.", ans: ["идут", "едут"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_7", ex: "Вы ________ в парк пешком?", ans: ["идёте", "едете"], tags: ["mode_foot", "dir_uni", "time_present", "dom_nature"] },
        { id: "v1_8", ex: "Мой хороший друг ________ в офис пешком.", ans: ["идёт", "едет"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_9", ex: "Мы с братом ________ в кино пешком.", ans: ["идём", "едем"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_10", ex: "Студенты ________ в библиотеку пешком.", ans: ["идут", "едут"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_11", ex: "Где мама? — Она ________ в аптеку пешком.", ans: ["идёт", "едет"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_12", ex: "Ты ________ в центр пешком?", ans: ["идёшь", "едешь"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_13", ex: "Этот высокий человек ________ в банк пешком.", ans: ["идёт", "едет"], tags: ["mode_foot", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_14", ex: "Наши дети ________ в парк пешком.", ans: ["идут", "едут"], tags: ["mode_foot", "dir_uni", "time_present", "dom_nature"] },
        { id: "v1_15", ex: "Я не еду на такси, я ________ пешком.", ans: ["иду", "еду"], tags: ["mode_foot", "dir_uni", "time_present", "logic_choice"] },
        { id: "v1_16", ex: "Мой папа ________ на работу на машине.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_17", ex: "Эта красная машина ________ в центр.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_city"] },
        { id: "v1_18", ex: "Я ________ в банк на такси.", ans: ["еду", "иду"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_19", ex: "Твой новый студент ________ в университет на метро.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_20", ex: "Этот синий автобус ________ в аэропорт.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_21", ex: "Вы ________ в офис на машине?", ans: ["едете", "идёте"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_22", ex: "Наши друзья ________ в ресторан на такси.", ans: ["едут", "идут"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_23", ex: "Мы сейчас ________ домой на автобусе.", ans: ["едем", "идём"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport", "mark_now"] },
        { id: "v1_24", ex: "Они ________ в центр на трамвае.", ans: ["едут", "идут"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_25", ex: "Ваши дети ________ в школу на автобусе?", ans: ["едут", "идут"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_26", ex: "Быстрое такси уже ________ в аэропорт.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport", "mark_now"] },
        { id: "v1_27", ex: "Ты ________ на работу на метро?", ans: ["едешь", "идёшь"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_28", ex: "Этот старый трамвай ________ в депо.", ans: ["едет", "идёт"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_29", ex: "Мы ________ в кафе на машине.", ans: ["едем", "идём"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport"] },
        { id: "v1_30", ex: "Они сейчас ________ в аэропорт на поезде.", ans: ["едут", "идут"], tags: ["mode_wheels", "dir_uni", "time_present", "dom_transport", "mark_now"] }
    ],

    // УРОК 2 (Индекс 1): ИДТИ • ХОДИТЬ (30 вопросов)
    [
        { exver: "Урок 2: ИДТИ • ХОДИТЬ (сейчас или обычно)" },
        { id: "v2_1", ex: "Я каждый день ________ в школу пешком.", ans: ["хожу", "иду"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_2", ex: "Мой папа часто ________ в этот банк.", ans: ["ходит", "идёт"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_3", ex: "Мы обычно ________ в парк по субботам.", ans: ["ходим", "идём"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_4", ex: "Вы редко ________ в музей?", ans: ["ходите", "идёте"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_5", ex: "Эти студенты каждый вечер ________ в библиотеку.", ans: ["ходят", "идут"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_6", ex: "Твоя сестра всегда ________ на работу через центр.", ans: ["ходит", "идёт"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_7", ex: "Я никогда не ________ в этот ресторан.", ans: ["хожу", "иду"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_8", ex: "Наши дети ________ в бассейн два раза в неделю.", ans: ["ходят", "идут"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_9", ex: "Ты часто ________ в кино?", ans: ["ходишь", "идёшь"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_10", ex: "Мы ________ в университет пешком каждое утро.", ans: ["ходим", "идём"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_11", ex: "Обычно мой друг ________ в спортзал вечером.", ans: ["ходит", "идёт"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_12", ex: "Маленькая девочка уже ________ в первый класс.", ans: ["ходит", "идёт"], tags: ["mode_foot", "dir_multi", "time_present", "dom_social"] },
        { id: "v2_13", ex: "Вы часто ________ на выставки?", ans: ["ходите", "идёте"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_14", ex: "Я всегда ________ в магазин рядом с домом.", ans: ["хожу", "иду"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_15", ex: "Они ________ гулять в парк каждое воскресенье.", ans: ["ходят", "идут"], tags: ["mode_foot", "dir_multi", "time_present", "mark_habit"] },
        { id: "v2_16", ex: "Смотри! Иван ________ в библиотеку.", ans: ["идёт", "ходит"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_17", ex: "Я сейчас ________ в аптеку, ты хочешь со мной?", ans: ["иду", "хожу"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_18", ex: "Где вы? — Мы ________ в театр, мы уже на улице.", ans: ["идём", "ходим"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_19", ex: "Куда ты ________? — В офис, у меня встреча.", ans: ["идёшь", "ходишь"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_20", ex: "Смотри, этот человек ________ очень быстро.", ans: ["идёт", "ходит"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_21", ex: "Мы сегодня ________ в музей, а завтра — в парк.", ans: ["идём", "ходим"], tags: ["mode_foot", "dir_uni", "time_present", "logic_plan"] },
        { id: "v2_22", ex: "Куда они ________? — На почту, они спешат.", ans: ["идут", "ходят"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_23", ex: "Подожди! Я тоже ________ в центр.", ans: ["иду", "хожу"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_24", ex: "Вы сейчас ________ на работу или домой?", ans: ["идёте", "ходите"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_25", ex: "Мой брат сейчас ________ в банк.", ans: ["идёт", "ходит"], tags: ["mode_foot", "dir_uni", "time_present", "mark_now"] },
        { id: "v2_26", ex: "Врачи говорят, что полезно ________ пешком 10 тысяч шагов каждый день.", ans: ["ходить", "идти"], tags: ["mode_foot", "dir_multi", "mark_habit"] },
        { id: "v2_27", ex: "Мой дедушка каждое утро ________ в магазин за свежими газетами.", ans: ["ходит", "идёт"], tags: ["mode_foot", "dir_multi", "mark_habit"] },
        { id: "v2_28", ex: "Мы с друзьями иногда ________ в горы в поход.", ans: ["ходим", "идём"], tags: ["mode_foot", "dir_multi", "mark_habit"] },
        { id: "v2_29", ex: "Как часто ты ________ в бассейн?", ans: ["ходишь", "идёшь"], tags: ["mode_foot", "dir_multi", "mark_habit"] },
        { id: "v2_30", ex: "Обычно я ________ на работу через этот старый мост.", ans: ["хожу", "иду"], tags: ["mode_foot", "dir_multi", "mark_habit"] }
    ],

    // УРОК 3 (Индекс 2): ПРОШЕДШЕЕ И БУДУЩЕЕ (30 вопросов)
    [
        { exver: "Урок 3: Прошедшее время: Ходил или Ездил" },
        { id: "v3_1", ex: "Вчера я ________ в музей пешком.", ans: ["ходил", "иду"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_2", ex: "Моя сестра вчера ________ в аптеку.", ans: ["ходила", "идет"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_3", ex: "Друзья ________ в парк в субботу.", ans: ["ходили", "идут"], tags: ["mode_foot", "time_past", "dom_nature"] },
        { id: "v3_4", ex: "Где ты был? — Я ________ в банк.", ans: ["ходил", "иду"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_5", ex: "Мы вчера ________ в школу пешком.", ans: ["ходили", "идем"], tags: ["mode_foot", "time_past", "dom_social"] },
        { id: "v3_6", ex: "Этот студент вчера ________ в библиотеку.", ans: ["ходил", "идет"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_7", ex: "Вы вчера ________ в кино?", ans: ["ходили", "идете"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_8", ex: "Маленькая девочка вчера ________ в зоопарк.", ans: ["ходила", "идет"], tags: ["mode_foot", "time_past", "dom_nature"] },
        { id: "v3_9", ex: "Раньше мы часто ________ в этот ресторан.", ans: ["ходили", "идем"], tags: ["mode_foot", "time_past", "mark_habit"] },
        { id: "v3_10", ex: "Вчера папа ________ на работу пешком.", ans: ["ходил", "идет"], tags: ["mode_foot", "time_past", "dom_city"] },
        { id: "v3_11", ex: "Прошлым летом мы ________ в Крым.", ans: ["ездили", "едем"], tags: ["mode_wheels", "time_past", "dom_nature"] },
        { id: "v3_12", ex: "Вчера мой друг ________ в офис на такси.", ans: ["ездил", "едет"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_13", ex: "Вы когда-нибудь ________ в Москву?", ans: ["ездили", "едете"], tags: ["mode_wheels", "time_past", "dom_city"] },
        { id: "v3_14", ex: "Я ________ в банк на машине вчера.", ans: ["ездил", "еду"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_15", ex: "Мои родители ________ на море в августе.", ans: ["ездили", "едут"], tags: ["mode_wheels", "time_past", "dom_nature"] },
        { id: "v3_16", ex: "Эта машина вчера ________ в центр города.", ans: ["ездила", "едет"], tags: ["mode_wheels", "time_past", "dom_city"] },
        { id: "v3_17", ex: "Мы ________ на выставку на автобусе.", ans: ["ездили", "едем"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_18", ex: "Вчера вы ________ в парк на метро?", ans: ["ездили", "едете"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_19", ex: "Студенты ________ в другой город на поезде.", ans: ["ездили", "едут"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_20", ex: "Мой брат ________ на стадион на велосипеде.", ans: ["ездил", "едет"], tags: ["mode_wheels", "time_past", "dom_transport"] },
        { id: "v3_21", ex: "Я ________ в магазин пешком вчера.", ans: ["ходил", "ездил"], tags: ["mode_foot", "time_past", "logic_choice"] },
        { id: "v3_22", ex: "Мы ________ в университет на автобусе.", ans: ["ездили", "ходили"], tags: ["mode_wheels", "time_past", "logic_choice"] },
        { id: "v3_23", ex: "Вчера она ________ на почту пешком.", ans: ["ходила", "ездила"], tags: ["mode_foot", "time_past", "logic_choice"] },
        { id: "v3_24", ex: "Вы ________ в центр на такси?", ans: ["ездили", "ходили"], tags: ["mode_wheels", "time_past", "logic_choice"] },
        { id: "v3_25", ex: "Мой папа ________ в банк на машине.", ans: ["ездил", "ходил"], tags: ["mode_wheels", "time_past", "logic_choice"] },
        { id: "v3_26", ex: "Друзья ________ в театр пешком.", ans: ["ходили", "ездили"], tags: ["mode_foot", "time_past", "logic_choice"] },
        { id: "v3_27", ex: "Завтра я ________ в парк пешком.", ans: ["пойду", "хожу"], tags: ["mode_foot", "time_future", "aspect_perf"] },
        { id: "v3_28", ex: "Завтра мы ________ в центр на машине.", ans: ["поедем", "ездим"], tags: ["mode_wheels", "time_future", "aspect_perf"] },
        { id: "v3_29", ex: "На прошлой неделе мы ________ в лес за грибами.", ans: ["ходили", "идем"], tags: ["mode_foot", "time_past"] },
        { id: "v3_30", ex: "— Где вы были вчера вечером? — Мы ________ на концерт классической музыки.", ans: ["ходили", "идем"], tags: ["mode_foot", "time_past"] }
    ],

    // УРОК 4 (Индекс 3): ПЕРЕНОС ПРЕДМЕТОВ (30 вопросов)
    [
        { exver: "Урок 4: Несу, веду или везу?" },
        { id: "v4_1", ex: "Мой папа сейчас ________ этот большой чемодан.", ans: ["несёт", "носит"], tags: ["obj_hand", "dir_uni", "time_present"] },
        { id: "v4_2", ex: "Обычно я ________ документы на работу в сумке.", ans: ["ношу", "несу"], tags: ["obj_hand", "dir_multi", "time_present", "mark_habit"] },
        { id: "v4_3", ex: "Смотри! Эта девочка ________ красивый цветок.", ans: ["несёт", "носит"], tags: ["obj_hand", "dir_uni", "time_present", "mark_now"] },
        { id: "v4_4", ex: "Мы всегда ________ школьную форму в лицей.", ans: ["носим", "несём"], tags: ["obj_hand", "dir_multi", "time_present", "dom_clothing"] },
        { id: "v4_5", ex: "Почему ты ________ этот тяжёлый пакет один?", ans: ["несёшь", "носишь"], tags: ["obj_hand", "dir_uni", "time_present"] },
        { id: "v4_6", ex: "Эта мама сейчас ________ маленького ребёнка в сад.", ans: ["ведёт", "водит"], tags: ["obj_lead", "dir_uni", "time_present"] },
        { id: "v4_7", ex: "Мой старший брат хорошо ________ машину.", ans: ["водит", "ведёт"], tags: ["obj_lead", "dir_multi", "time_present", "logic_skill"] },
        { id: "v4_8", ex: "Я часто ________ свою собаку в парк гулять.", ans: ["вожу", "веду"], tags: ["obj_lead", "dir_multi", "time_present", "dom_nature"] },
        { id: "v4_9", ex: "Смотри, полиция ________ этого человека.", ans: ["ведёт", "водит"], tags: ["obj_lead", "dir_uni", "time_present", "mark_now"] },
        { id: "v4_10", ex: "Вы уже ________ машину или ещё учитесь?", ans: ["водите", "ведёте"], tags: ["obj_lead", "dir_multi", "time_present", "logic_skill"] },
        { id: "v4_11", ex: "Этот синий автобус сейчас ________ туристов в центр.", ans: ["везёт", "возит"], tags: ["obj_cargo", "dir_uni", "time_present", "dom_transport"] },
        { id: "v4_12", ex: "Грузовики каждый день ________ продукты в магазин.", ans: ["возят", "везут"], tags: ["obj_cargo", "dir_multi", "time_present", "dom_transport"] },
        { id: "v4_13", ex: "Я сейчас ________ брата в аэропорт на машине.", ans: ["везу", "вожу"], tags: ["obj_cargo", "dir_uni", "time_present", "dom_transport"] },
        { id: "v4_14", ex: "Такси ________ нас очень быстро.", ans: ["везёт", "возит"], tags: ["obj_cargo", "dir_uni", "time_present", "dom_transport"] },
        { id: "v4_15", ex: "Я пешком, я ________ сумку в руках.", ans: ["несу", "везу"], tags: ["obj_hand", "mode_foot", "logic_choice"] },
        { id: "v4_16", ex: "Я на машине, я ________ сумку в багажнике.", ans: ["везу", "несу"], tags: ["obj_cargo", "mode_wheels", "logic_choice"] },
        { id: "v4_17", ex: "Отец ________ сына за руку через дорогу.", ans: ["ведёт", "везёт"], tags: ["obj_lead", "mode_foot", "logic_choice"] },
        { id: "v4_18", ex: "Автобус ________ детей в школу.", ans: ["везёт", "ведёт"], tags: ["obj_cargo", "mode_wheels", "logic_choice"] },
        { id: "v4_19", ex: "Каждое утро я ________ собаку на улицу.", ans: ["вожу", "ношу"], tags: ["obj_lead", "mark_habit", "logic_choice"] },
        { id: "v4_20", ex: "Этот курьер ________ еду из ресторана пешком.", ans: ["несёт", "везёт"], tags: ["obj_hand", "mode_foot", "dom_city"] },
        { id: "v4_21", ex: "Пилоты ________ самолёты очень профессионально.", ans: ["водят", "носят"], tags: ["obj_lead", "logic_skill", "dom_transport"] },
        { id: "v4_22", ex: "Бабушка часто ________ нам вкусные пирожки.", ans: ["возит", "ведёт"], tags: ["obj_cargo", "mark_habit", "dom_social"] },
        { id: "v4_23", ex: "Я сейчас ________ продукты домой из магазина.", ans: ["несу", "вожу"], tags: ["obj_hand", "dir_uni", "mark_now"] },
        { id: "v4_24", ex: "Ты часто ________ очки или только когда читаешь?", ans: ["носишь", "несёшь"], tags: ["obj_hand", "dom_clothing", "mark_habit"] },
        { id: "v4_25", ex: "Этот трамвай ________ людей в парк.", ans: ["везёт", "несёт"], tags: ["obj_cargo", "dom_transport"] },
        { id: "v4_26", ex: "Мы ________ старую мебель на дачу на грузовике.", ans: ["возим", "носим"], tags: ["obj_cargo", "dom_transport", "mark_habit"] },
        { id: "v4_27", ex: "Официант быстро ________ поднос с напитками к нашему столу.", ans: ["несёт", "водит"], tags: ["obj_hand", "dir_uni"] },
        { id: "v4_28", ex: "Опытный капитан ________ огромный корабль через океан.", ans: ["ведёт", "везёт"], tags: ["obj_lead", "dir_uni"] },
        { id: "v4_29", ex: "Машина службы доставки сейчас ________ нам новую кровать.", ans: ["везёт", "несёт"], tags: ["obj_cargo", "dir_uni"] },
        { id: "v4_30", ex: "Бабушка внимательно ________ маленькую внучку за руку через дорогу.", ans: ["ведёт", "везёт"], tags: ["obj_lead", "dir_uni"] }
    ],

    // УРОК 5 (Индекс 4): ПЕРЕНОСНЫЕ ЗНАЧЕНИЯ (20 вопросов)
    [
        { exver: "Урок 5: Когда 'идти' — это не пешком" },
        { id: "v5_1", ex: "Посмотри в окно! Там ________ сильный снег.", ans: ["идёт", "едет"], tags: ["dom_nature", "weather", "time_present"] },
        { id: "v5_2", ex: "Вчера весь день ________ холодный дождь.", ans: ["шёл", "был"], tags: ["dom_nature", "weather", "time_past"] },
        { id: "v5_3", ex: "Обычно осенью часто ________ дождь.", ans: ["идёт", "плывёт"], tags: ["dom_nature", "weather", "mark_habit"] },
        { id: "v5_4", ex: "Как быстро ________ время в отпуске!", ans: ["идёт", "бежит"], tags: ["dom_abstract", "time_concept"] },
        { id: "v5_5", ex: "Мои старые часы ________ очень точно.", ans: ["идут", "ходят"], tags: ["dom_abstract", "technology"] },
        { id: "v5_6", ex: "Минуты ________ медленно, когда я тебя жду.", ans: ["идут", "едут"], tags: ["dom_abstract", "time_concept"] },
        { id: "v5_7", ex: "Твои часы не ________, там нет батарейки.", ans: ["идут", "стоят"], tags: ["dom_abstract", "technology"] },
        { id: "v5_8", ex: "Сейчас в кинотеатре ________ новый фильм.", ans: ["идёт", "едет"], tags: ["dom_abstract", "culture"] },
        { id: "v5_9", ex: "В театре сегодня ________ опера 'Кармен'.", ans: ["идёт", "плывёт"], tags: ["dom_abstract", "culture"] },
        { id: "id_10", ex: "Завтра в музее ________ интересная выставка.", ans: ["пойдёт", "поедет"], tags: ["dom_abstract", "culture", "time_future"] },
        { id: "v5_11", ex: "Это синее платье тебе очень ________.", ans: ["идёт", "несёт"], tags: ["dom_clothing", "appearance"] },
        { id: "v5_12", ex: "Твоему папе очень ________ этот костюм.", ans: ["идёт", "везёт"], tags: ["dom_clothing", "appearance"] },
        { id: "v5_13", ex: "Тебе совсем не ________ эта старая шапка.", ans: ["идёт", "ведёт"], tags: ["dom_clothing", "appearance"] },
        { id: "v5_14", ex: "Твоей маме ________ новая короткая причёска.", ans: ["идёт", "ведёт"], tags: ["dom_clothing", "appearance"] },
        { id: "v5_15", ex: "Время ________, нам пора домой.", ans: ["идёт", "едет"], tags: ["dom_abstract", "time_concept"] },
        { id: "v5_16", ex: "Смотри, на улице ________ первый снег!", ans: ["идёт", "летит"], tags: ["dom_nature", "weather", "mark_now"] },
        { id: "v5_17", ex: "Этот яркий цвет тебе совсем не ________.", ans: ["идёт", "носит"], tags: ["dom_clothing", "appearance"] },
        { id: "v5_18", ex: "Вчера в клубе ________ отличный концерт.", ans: ["шёл", "ехал"], tags: ["dom_abstract", "culture", "time_past"] },
        { id: "v5_19", ex: "Где мои часы? Я хочу знать, как они ________.", ans: ["идут", "плывут"], tags: ["dom_abstract", "technology"] },
        { id: "v5_20", ex: "Простите, а о чём сейчас ________ речь? Я не понимаю.", ans: ["идёт", "едет"], tags: ["dom_abstract", "logic_phrase"] }
    ],

    // ЭКЗАМЕН 1 (Индекс 5)
    [{ exver: "Тренировка" }]
];