/**
 * Learn & Go - Глаголы движения с приставками
 * Файл: data_prefixes.js
 */

upr.push(
    // УРОК 6: Вход и Выход (В- / ВЫ-)
    [
        { exver: "Урок 6: Вход и Выход (В- / ВЫ-)" },
        { id: "p6_1", ex: "Подождите на улице, я сейчас ________ из дома.", ans: ["выйду", "войду"], tags: ["prefix_out", "mode_foot", "time_future", "dom_social"] },
        { id: "p6_2", ex: "На улице холодно, пожалуйста, ________ в кафе.", ans: ["войдите", "выйдите"], tags: ["prefix_in", "mode_foot", "time_present", "dom_city"] },
        { id: "p6_3", ex: "Он ________ в кабинет и закрыл дверь.", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_4", ex: "Мама вчера поздно ________ из офиса.", ans: ["вышла", "вошла"], tags: ["prefix_out", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_5", ex: "Машина медленно ________ в гараж.", ans: ["въехала", "выехала"], tags: ["prefix_in", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p6_6", ex: "Автобус уже ________ из депо на маршрут.", ans: ["выехал", "въехал"], tags: ["prefix_out", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p6_7", ex: "Мы ________ из метро на станции 'Арбатская'.", ans: ["вышли", "вошли"], tags: ["prefix_out", "mode_foot", "time_past", "dom_transport"] },
        { id: "p6_8", ex: "Студенты ________ в аудиторию и сели.", ans: ["вошли", "вышли"], tags: ["prefix_in", "mode_foot", "time_past", "dom_social"] },
        { id: "p6_9", ex: "Я забыл ключи и ________ обратно в дом.", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_foot", "time_past", "dom_social"] },
        { id: "p6_10", ex: "Осторожно! Птица ________ в окно.", ans: ["влетела", "вылетела"], tags: ["prefix_in", "mode_air", "time_past", "dom_nature"] },
        { id: "p6_11", ex: "Поезд быстро ________ в туннель.", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p6_12", ex: "Зрители ________ из театра после спектакля.", ans: ["вышли", "вошли"], tags: ["prefix_out", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_13", ex: "Кот увидел собаку и ________ в сад.", ans: ["выбежал", "вбежал"], tags: ["prefix_out", "mode_foot", "time_past", "dom_nature"] },
        { id: "p6_14", ex: "Малыш тихо ________ в комнату к маме.", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_foot", "time_past", "dom_social"] },
        { id: "p6_15", ex: "Вы уже ________ из игры?", ans: ["вышли", "вошли"], tags: ["prefix_out", "mode_foot", "time_present", "dom_abstract"] },
        { id: "p6_16", ex: "Солнце наконец ________ из-за туч.", ans: ["вышло", "вошло"], tags: ["prefix_out", "mode_foot", "time_past", "dom_nature"] },
        { id: "p6_17", ex: "Корабль утром ________ в порт.", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_water", "time_past", "dom_transport"] },
        { id: "p6_18", ex: "Официант ________ из кухни с заказом.", ans: ["вышел", "вошёл"], tags: ["prefix_out", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_19", ex: "Я хочу ________ из этой группы.", ans: ["выйти", "войти"], tags: ["prefix_out", "mode_foot", "time_future", "dom_abstract"] },
        { id: "p6_20", ex: "Папа ________ машину в гараж.", ans: ["въехал", "выехал"], tags: ["prefix_in", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p6_21", ex: "Смотри, кто ________ в магазин сейчас?", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_22", ex: "Мы ________ из лифта на пятом этаже.", ans: ["вышли", "вошли"], tags: ["prefix_out", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_23", ex: "Туристы ________ в отель поздно вечером.", ans: ["вошли", "вышли"], tags: ["prefix_in", "mode_foot", "time_past", "dom_transport"] },
        { id: "p6_24", ex: "Кровь ________ из раны.", ans: ["вышла", "вошла"], tags: ["prefix_out", "mode_water", "time_past", "dom_abstract"] },
        { id: "p6_25", ex: "Дым ________ из трубы.", ans: ["вышел", "вошёл"], tags: ["prefix_out", "mode_air", "time_past", "dom_nature"] },
        { id: "p6_26", ex: "Пожалуйста, ________ из кабинета!", ans: ["выйдите", "войдите"], tags: ["prefix_out", "mode_foot", "time_present", "dom_city"] },
        { id: "p6_27", ex: "Вода быстро ________ в трубу.", ans: ["вошла", "вышла"], tags: ["prefix_in", "mode_water", "time_past", "dom_nature"] },
        { id: "p6_28", ex: "Эта новость скоро ________ в историю.", ans: ["войдёт", "выйдет"], tags: ["prefix_in", "mode_foot", "time_future", "dom_abstract"] },
        { id: "p6_29", ex: "Мы ________ из очереди в банке.", ans: ["вышли", "вошли"], tags: ["prefix_out", "mode_foot", "time_past", "dom_city"] },
        { id: "p6_30", ex: "Кто ________ в твой аккаунт без пароля?", ans: ["вошёл", "вышел"], tags: ["prefix_in", "mode_foot", "time_past", "dom_abstract"] }
    ],

    // УРОК 7: Прибытие и Уход (ПРИ- / У-)
    [
        { exver: "Урок 7: Прибытие и Уход (ПРИ- / У-)" },
        { id: "p7_1", ex: "Он был тут, а сейчас его нет. Он ________.", ans: ["ушёл", "пришёл"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_2", ex: "Смотри! Папа уже ________, он дома.", ans: ["пришёл", "ушёл"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_3", ex: "Мой друг вчера ________ из России в Китай.", ans: ["уехал", "приехал"], tags: ["prefix_departure", "mode_wheels", "time_past", "dom_nature"] },
        { id: "p7_4", ex: "Вчера к нам ________ гости из Москвы.", ans: ["приехали", "уехали"], tags: ["prefix_arrival", "mode_wheels", "time_past", "dom_social"] },
        { id: "p7_5", ex: "Когда твои друзья ________ к нам на ужин?", ans: ["придут", "уйдут"], tags: ["prefix_arrival", "mode_foot", "time_future", "dom_social"] },
        { id: "p7_6", ex: "Поезд уже ________, платформа пустая.", ans: ["ушёл", "пришёл"], tags: ["prefix_departure", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p7_7", ex: "Я очень рад, что вы ________ сегодня!", ans: ["пришли", "ушли"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_8", ex: "Где Виктор? — Он ________ из офиса час назад.", ans: ["ушёл", "пришёл"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_city"] },
        { id: "p7_9", ex: "Такси ________ через 5 минут, выходи.", ans: ["приедет", "уедет"], tags: ["prefix_arrival", "mode_wheels", "time_future", "dom_transport"] },
        { id: "p7_10", ex: "Она ________ из школы в 3 часа дня.", ans: ["ушла", "пришла"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_11", ex: "Самолёт ________ вовремя по расписанию.", ans: ["прилетел", "улетел"], tags: ["prefix_arrival", "mode_air", "time_past", "dom_transport"] },
        { id: "p7_12", ex: "Птицы осенью ________ на юг.", ans: ["улетают", "прилетают"], tags: ["prefix_departure", "mode_air", "time_present", "dom_nature"] },
        { id: "p7_13", ex: "Письмо ________ вчера вечером.", ans: ["пришло", "ушло"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p7_14", ex: "Пора ________, такси уже ждёт.", ans: ["уходить", "приходить"], tags: ["prefix_departure", "mode_foot", "time_present", "dom_transport"] },
        { id: "p7_15", ex: "К нам ________ новый преподаватель.", ans: ["пришёл", "ушёл"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_16", ex: "Зима ________ внезапно в этом году.", ans: ["пришла", "ушла"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_nature"] },
        { id: "p7_17", ex: "Корабль ________ в порт утром.", ans: ["пришёл", "ушёл"], tags: ["prefix_arrival", "mode_water", "time_past", "dom_transport"] },
        { id: "p7_18", ex: "Родители ________ на работу рано.", ans: ["ушли", "пришли"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_19", ex: "Я ________ на вокзал за 10 минут до поезда.", ans: ["пришёл", "ушёл"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_transport"] },
        { id: "p7_20", ex: "Вы ________ в Петербург на неделю?", ans: ["приехали", "уехали"], tags: ["prefix_arrival", "mode_wheels", "time_past", "dom_city"] },
        { id: "p7_21", ex: "Счастье наконец ________ в наш дом.", ans: ["пришло", "ушло"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p7_22", ex: "Автобус ________ от остановки.", ans: ["уехал", "приехал"], tags: ["prefix_departure", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p7_23", ex: "Он ________ из команды навсегда.", ans: ["ушёл", "пришёл"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p7_24", ex: "Мы ________ в Сочи на самолёте.", ans: ["прилетели", "улетели"], tags: ["prefix_arrival", "mode_air", "time_past", "dom_nature"] },
        { id: "p7_25", ex: "Когда ________ посылка из Китая?", ans: ["придёт", "уйдёт"], tags: ["prefix_arrival", "mode_foot", "time_future", "dom_abstract"] },
        { id: "p7_26", ex: "Дети ________ в школу пешком.", ans: ["ушли", "пришли"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_social"] },
        { id: "p7_27", ex: "Вечер ________ незаметно.", ans: ["пришёл", "ушёл"], tags: ["prefix_arrival", "mode_foot", "time_past", "dom_nature"] },
        { id: "p7_28", ex: "Она ________ в магазин за хлебом.", ans: ["ушла", "пришла"], tags: ["prefix_departure", "mode_foot", "time_past", "dom_city"] },
        { id: "p7_29", ex: "Мы ________ в Питер на праздники.", ans: ["приехали", "уехали"], tags: ["prefix_arrival", "mode_wheels", "time_past", "dom_city"] },
        { id: "p7_30", ex: "Лето скоро ________.", ans: ["уйдёт", "придёт"], tags: ["prefix_departure", "mode_foot", "time_future", "dom_nature"] }
    ],

    // УРОК 8: Приближение и Отдаление (ПОД- / ОТ-)
    [
        { exver: "Урок 8: Приближение и Отдаление (ПОД- / ОТ-)" },
        { id: "p8_1", ex: "Я ________ к киоску за журналом.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_city"] },
        { id: "p8_2", ex: "Машина ________ от подъезда.", ans: ["отъехала", "подъехала"], tags: ["prefix_distancing", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_3", ex: "Студент ________ к доске отвечать.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_4", ex: "Поезд ________ к платформе номер 5.", ans: ["подъехал", "отъехал"], tags: ["prefix_approach", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_5", ex: "Отойди, пожалуйста, ________ от окна.", ans: ["отойди", "подойди"], tags: ["prefix_distancing", "mode_foot", "time_present", "dom_city"] },
        { id: "p8_6", ex: "Корабль ________ от берега.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_water", "time_past", "dom_nature"] },
        { id: "p8_7", ex: "Мама ________ к плите готовить обед.", ans: ["подошла", "отошла"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_8", ex: "Лодка ________ к причалу.", ans: ["подплыла", "отплыла"], tags: ["prefix_approach", "mode_water", "time_past", "dom_nature"] },
        { id: "p8_9", ex: "Он ________ от темы нашего разговора.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p8_10", ex: "Мы ________ к самому входу в парк.", ans: ["подошли", "отошли"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_nature"] },
        { id: "p8_11", ex: "Такси ________ к парадной.", ans: ["подъехали", "отъехали"], tags: ["prefix_approach", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_12", ex: "Пожалуйста, ________ поближе ко мне.", ans: ["подойди", "отойди"], tags: ["prefix_approach", "mode_foot", "time_present", "dom_social"] },
        { id: "p8_13", ex: "Птица ________ к хлебу на земле.", ans: ["подлетела", "отлетела"], tags: ["prefix_approach", "mode_air", "time_past", "dom_nature"] },
        { id: "p8_14", ex: "Он ________ от зеркала и улыбнулся.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_15", ex: "Мы ________ к решению этой задачи.", ans: ["подошли", "отошли"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p8_16", ex: "Машина ________ от заправки.", ans: ["отъехала", "подъехала"], tags: ["prefix_distancing", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_17", ex: "Сын ________ к отцу за советом.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_18", ex: "Облако ________ к солнцу.", ans: ["подошло", "отошло"], tags: ["prefix_approach", "mode_air", "time_past", "dom_nature"] },
        { id: "p8_19", ex: "Автобус ________ к остановке.", ans: ["подъехал", "отъехал"], tags: ["prefix_approach", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_20", ex: "Я ________ от края платформы.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_foot", "time_past", "dom_transport"] },
        { id: "p8_21", ex: "Девушка ________ к витрине магазина.", ans: ["подошла", "отошла"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_city"] },
        { id: "p8_22", ex: "Пароход ________ от пристани.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_water", "time_past", "dom_transport"] },
        { id: "p8_23", ex: "Он ________ к двери и постучал.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_24", ex: "Мы ________ от берега на 100 метров.", ans: ["отплыли", "подплыли"], tags: ["prefix_distancing", "mode_water", "time_past", "dom_nature"] },
        { id: "p8_25", ex: "Кот ________ к миске с едой.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_nature"] },
        { id: "p8_26", ex: "Машина ________ к светофору.", ans: ["подъехала", "отъехала"], tags: ["prefix_approach", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_27", ex: "Она ________ от окна и села на диван.", ans: ["отошла", "подошла"], tags: ["prefix_distancing", "mode_foot", "time_past", "dom_social"] },
        { id: "p8_28", ex: "Мы ________ к концу этого урока.", ans: ["подошли", "отошли"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p8_29", ex: "Поезд ________ от станции вовремя.", ans: ["отошёл", "подошёл"], tags: ["prefix_distancing", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p8_30", ex: "Я ________ к кассе купить билет.", ans: ["подошёл", "отошёл"], tags: ["prefix_approach", "mode_foot", "time_past", "dom_city"] }
    ],

    // УРОК 9: Сложные маршруты (ПЕРЕ-, ДО-, ЗА-, ПРО-)
    [
        { exver: "Урок 9: Сложные маршруты (ПЕРЕ-, ДО-, ЗА-, ПРО-)" },
        { id: "p9_1", ex: "Нам нужно ________ эту дорогу по переходу.", ans: ["перейти", "зайти"], tags: ["prefix_pere", "mode_foot", "time_future", "dom_city"] },
        { id: "p9_2", ex: "Как ________ до ближайшей аптеки?", ans: ["дойти", "зайти"], tags: ["prefix_do", "mode_foot", "time_future", "dom_city"] },
        { id: "p9_3", ex: "Я ________ в магазин за водой на минуту.", ans: ["зайду", "пройду"], tags: ["prefix_za", "mode_foot", "time_future", "dom_city"] },
        { id: "p9_4", ex: "Мы ________ мимо Большого театра.", ans: ["прошли", "перешли"], tags: ["prefix_pro", "mode_foot", "time_past", "dom_city"] },
        { id: "p9_5", ex: "Нужно ________ на другую сторону улицы.", ans: ["перейти", "дойти"], tags: ["prefix_pere", "mode_foot", "time_future", "dom_city"] },
        { id: "p9_6", ex: "Мы ________ до конца Невского проспекта.", ans: ["дошли", "прошли"], tags: ["prefix_do", "mode_foot", "time_past", "dom_city"] },
        { id: "p9_7", ex: "Автомобиль ________ перекресток.", ans: ["проехал", "переехал"], tags: ["prefix_pro", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p9_8", ex: "Семья ________ в новую квартиру.", ans: ["переехала", "заехала"], tags: ["prefix_pere", "mode_wheels", "time_past", "dom_social"] },
        { id: "p9_9", ex: "Я ________ за тобой в 8 вечера.", ans: ["зайду", "дойду"], tags: ["prefix_za", "mode_foot", "time_future", "dom_social"] },
        { id: "p9_10", ex: "Мы ________ через мост.", ans: ["перешли", "прошли"], tags: ["prefix_pere", "mode_foot", "time_past", "dom_city"] },
        { id: "p9_11", ex: "Как ________ до вокзала на метро?", ans: ["доехать", "проехать"], tags: ["prefix_do", "mode_wheels", "time_future", "dom_transport"] },
        { id: "p9_12", ex: "Он ________ мимо меня и не поздоровался.", ans: ["прошёл", "зашёл"], tags: ["prefix_pro", "mode_foot", "time_past", "dom_social"] },
        { id: "p9_13", ex: "Мы ________ реку на лодке.", ans: ["переплыли", "проплыли"], tags: ["prefix_pere", "mode_water", "time_past", "dom_nature"] },
        { id: "p9_14", ex: "Я ________ до финиша первым.", ans: ["добежал", "перебежал"], tags: ["prefix_do", "mode_foot", "time_past", "dom_abstract"] },
        { id: "p9_15", ex: "По пути домой ________ на почту за посылкой.", ans: ["зайди", "пройди"], tags: ["prefix_za", "mode_foot", "time_present", "dom_city"] },
        { id: "p9_16", ex: "Нужно ________ этот туннель.", ans: ["проехать", "заехать"], tags: ["prefix_pro", "mode_wheels", "time_future", "dom_transport"] },
        { id: "p9_17", ex: "Мы ________ границу вечером.", ans: ["перешли", "дошли"], tags: ["prefix_pere", "mode_foot", "time_past", "dom_nature"] },
        { id: "p9_18", ex: "Он ________ через всю страну на машине.", ans: ["проехал", "переехал"], tags: ["prefix_pro", "mode_wheels", "time_past", "dom_nature"] },
        { id: "p9_19", ex: "Я ________ до дома за 10 минут.", ans: ["дошёл", "прошёл"], tags: ["prefix_do", "mode_foot", "time_past", "dom_social"] },
        { id: "p9_20", ex: "Они ________ мост на велосипедах.", ans: ["переехали", "проехали"], tags: ["prefix_pere", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p9_21", ex: "Пожалуйста, ________ в отдел кадров.", ans: ["зайдите", "пройдите"], tags: ["prefix_za", "mode_foot", "time_present", "dom_city"] },
        { id: "p9_22", ex: "Мы ________ мимо остановки и опоздали.", ans: ["проехали", "переехали"], tags: ["prefix_pro", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p9_23", ex: "Нужно ________ через эту площадь.", ans: ["пройти", "зайти"], tags: ["prefix_pro", "mode_foot", "time_future", "dom_city"] },
        { id: "p9_24", ex: "Он ________ в гости к другу на час.", ans: ["зашёл", "прошёл"], tags: ["prefix_za", "mode_foot", "time_past", "dom_social"] },
        { id: "p9_25", ex: "Мы ________ до озера через лес.", ans: ["дошли", "перешли"], tags: ["prefix_do", "mode_foot", "time_past", "dom_nature"] },
        { id: "p9_26", ex: "Автобус ________ мимо нас.", ans: ["проехал", "переехал"], tags: ["prefix_pro", "mode_wheels", "time_past", "dom_transport"] },
        { id: "p9_27", ex: "Я ________ дорогу в неположенном месте.", ans: ["перешёл", "дошёл"], tags: ["prefix_pere", "mode_foot", "time_past", "dom_city"] },
        { id: "p9_28", ex: "Нужно ________ 10 километров пешком.", ans: ["пройти", "зайти"], tags: ["prefix_pro", "mode_foot", "time_future", "dom_abstract"] },
        { id: "p9_29", ex: "Мы ________ до вершины горы.", ans: ["дошли", "прошли"], tags: ["prefix_do", "mode_foot", "time_past", "dom_nature"] },
        { id: "p9_30", ex: "Он ________ через парк к метро.", ans: ["прошёл", "перешёл"], tags: ["prefix_pro", "mode_foot", "time_past", "dom_city"] }
    ],

    // ФИНАЛЬНЫЙ ЭКЗАМЕН
    [{ exver: "Тренировка" }]
);